name: Fix Line Endings

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  convert_line_endings:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Convert line endings to Unix
        run: |
          sed -i 's/\r$//' ./.github/workflows/check-complete.bash
          
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/check-complete.bash
          git commit -m "Fix line endings for check-complete.bash"
          git push
